apiVersion: v1
kind: Pod
metadata:
  name: port-conflict-pod
spec:
  containers:
  - name: nginx-1 
    image: nginx
    ports:
    - containerPort: 80
  - name: nginx2 
    image: nginx
    ports:
    - containerPort: 80

