apiVersion: v1
kind: Pod
metadata:
  name: resource-over-request-pod
spec:
  containers:
  - name: resource-hungry-container
    image: nginx
    resources:
      requests:
        memory: "100Gi"
        cpu: "8"

