FROM python

ARG workdir=/app/

WORKDIR $workdir

RUN useradd -ms /bin/bash pyuser
RUN chown -R pyuser:pyuser $workdir
RUN chmod 755 $workdir
USER pyuser

RUN pip install --upgrade pip

COPY requirements/requirements.txt $workdir
RUN pip install -r requirements.txt

COPY . $workdir


CMD ["celery", "-A", "app", "beat", "--loglevel=info", "--scheduler" , "django_celery_beat.schedulers:DatabaseScheduler"]

