apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-dev
  labels:
    app: redis-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-dev
  template:
    metadata:
      labels:
        app: redis-dev
    spec:
      containers:
        - name: redis-dev
          image: redis:latest
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "0.5"
              memory: 1Gi
            limits:
              cpu: "1"
              memory: 2Gi
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: vikara-redis-dev
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: redis-dev
