apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        env:
        - name: asen
          value: pesho
        - name: ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: nginx-config
              key: env
        volumeMounts:
        - name: nginx-html-volume
          mountPath: /usr/share/nginx/html/index.html
          subPath: index.html
      volumes:
      - name: nginx-html-volume
        secret:
          secretName: nginx-html-secret

